networks:
  dev:

services:
  backend:
    build:
      context: ./kinokus-api
    image: deniszakharov2121/kinokus-api
    env_file:
      - kinokus-api/.env.prod
    volumes:
      - bundle_data:/usr/local/bundle
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - dev
    command: bin/docker-entrypoint

  frontend:
    build:
      context: ./kinokus-spa
    image: deniszakharov2121/kinokus-spa
    env_file:
      - kinokus-spa/.env
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev

  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev

volumes:
  db_data:
  bundle_data:
