version: "3.8"
networks:
  dev:

services:
  backend:
    build:
      context: ./kinokus-api
      dockerfile: Dockerfile
    image: deniszakharov2121/kinokus-api
    container_name: backend
    restart: unless-stopped
    env_file:
      - kinokus-api/.env.prod
    volumes:
      - ./backend:/app
      - bundle_data:/usr/local/bundle
      - ./backend/tmp/pids:/app/tmp/pids
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - dev

  frontend:
    build:
      context: ./kinokus-spa
      dockerfile: Dockerfile
    image: deniszakharov2121/kinokus-spa
    container_name: frontend
    restart: unless-stopped
    env_file:
      - kinokus-spa/.env
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev

  db:
    env_file:
      - kinokus-api/.env
    image: postgres:14
    container_name: db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev

volumes:
  db_data:
  bundle_data:
